/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Security.Client;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing ContentThreatDetectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ContentThreatDetectionApiTests
    {
        private ContentThreatDetectionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ContentThreatDetectionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContentThreatDetectionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ContentThreatDetectionApi
            //Assert.IsInstanceOfType(typeof(ContentThreatDetectionApi), instance, "instance is a ContentThreatDetectionApi");
        }

        
        /// <summary>
        /// Test ContentThreatDetectionAutomaticThreatDetectionString
        /// </summary>
        [Test]
        public void ContentThreatDetectionAutomaticThreatDetectionStringTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.ContentThreatDetectionAutomaticThreatDetectionString(value);
            //Assert.IsInstanceOf<StringAutomaticThreatDetection> (response, "response is StringAutomaticThreatDetection");
        }
        
        /// <summary>
        /// Test ContentThreatDetectionCheckSqlInjectionString
        /// </summary>
        [Test]
        public void ContentThreatDetectionCheckSqlInjectionStringTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.ContentThreatDetectionCheckSqlInjectionString(value);
            //Assert.IsInstanceOf<StringSqlInjectionDetectionResult> (response, "response is StringSqlInjectionDetectionResult");
        }
        
        /// <summary>
        /// Test ContentThreatDetectionCheckXxe
        /// </summary>
        [Test]
        public void ContentThreatDetectionCheckXxeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.ContentThreatDetectionCheckXxe(value);
            //Assert.IsInstanceOf<StringXxeDetectionResult> (response, "response is StringXxeDetectionResult");
        }
        
        /// <summary>
        /// Test ContentThreatDetectionDetectInsecureDeserializationJsonString
        /// </summary>
        [Test]
        public void ContentThreatDetectionDetectInsecureDeserializationJsonStringTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.ContentThreatDetectionDetectInsecureDeserializationJsonString(value);
            //Assert.IsInstanceOf<StringInsecureDeserializationJsonDetection> (response, "response is StringInsecureDeserializationJsonDetection");
        }
        
        /// <summary>
        /// Test ContentThreatDetectionProtectXss
        /// </summary>
        [Test]
        public void ContentThreatDetectionProtectXssTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.ContentThreatDetectionProtectXss(value);
            //Assert.IsInstanceOf<StringXssProtectionResult> (response, "response is StringXssProtectionResult");
        }
        
    }

}
