/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Security.Client;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing NetworkThreatDetectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NetworkThreatDetectionApiTests
    {
        private NetworkThreatDetectionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NetworkThreatDetectionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkThreatDetectionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NetworkThreatDetectionApi
            //Assert.IsInstanceOfType(typeof(NetworkThreatDetectionApi), instance, "instance is a NetworkThreatDetectionApi");
        }

        
        /// <summary>
        /// Test NetworkThreatDetectionDetectSsrfUrl
        /// </summary>
        [Test]
        public void NetworkThreatDetectionDetectSsrfUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UrlSsrfThreatDetectionRequestFull request = null;
            //var response = instance.NetworkThreatDetectionDetectSsrfUrl(request);
            //Assert.IsInstanceOf<UrlSsrfThreatDetectionResponseFull> (response, "response is UrlSsrfThreatDetectionResponseFull");
        }
        
        /// <summary>
        /// Test NetworkThreatDetectionIsBot
        /// </summary>
        [Test]
        public void NetworkThreatDetectionIsBotTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.NetworkThreatDetectionIsBot(value);
            //Assert.IsInstanceOf<ThreatDetectionBotCheckResponse> (response, "response is ThreatDetectionBotCheckResponse");
        }
        
        /// <summary>
        /// Test NetworkThreatDetectionIsThreat
        /// </summary>
        [Test]
        public void NetworkThreatDetectionIsThreatTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.NetworkThreatDetectionIsThreat(value);
            //Assert.IsInstanceOf<IPThreatDetectionResponse> (response, "response is IPThreatDetectionResponse");
        }
        
        /// <summary>
        /// Test NetworkThreatDetectionIsTorNode
        /// </summary>
        [Test]
        public void NetworkThreatDetectionIsTorNodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string value = null;
            //var response = instance.NetworkThreatDetectionIsTorNode(value);
            //Assert.IsInstanceOf<ThreatDetectionTorNodeResponse> (response, "response is ThreatDetectionTorNodeResponse");
        }
        
    }

}
