/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing IPThreatDetectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IPThreatDetectionResponseTests
    {
        // TODO uncomment below to declare an instance variable for IPThreatDetectionResponse
        //private IPThreatDetectionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IPThreatDetectionResponse
            //instance = new IPThreatDetectionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IPThreatDetectionResponse
        /// </summary>
        [Test]
        public void IPThreatDetectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IPThreatDetectionResponse
            //Assert.IsInstanceOfType<IPThreatDetectionResponse> (instance, "variable 'instance' is a IPThreatDetectionResponse");
        }


        /// <summary>
        /// Test the property 'IsThreat'
        /// </summary>
        [Test]
        public void IsThreatTest()
        {
            // TODO unit test for the property 'IsThreat'
        }
        /// <summary>
        /// Test the property 'ThreatType'
        /// </summary>
        [Test]
        public void ThreatTypeTest()
        {
            // TODO unit test for the property 'ThreatType'
        }

    }

}
