/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing StringXssProtectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StringXssProtectionResultTests
    {
        // TODO uncomment below to declare an instance variable for StringXssProtectionResult
        //private StringXssProtectionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StringXssProtectionResult
            //instance = new StringXssProtectionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StringXssProtectionResult
        /// </summary>
        [Test]
        public void StringXssProtectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StringXssProtectionResult
            //Assert.IsInstanceOfType<StringXssProtectionResult> (instance, "variable 'instance' is a StringXssProtectionResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'ContainedXss'
        /// </summary>
        [Test]
        public void ContainedXssTest()
        {
            // TODO unit test for the property 'ContainedXss'
        }
        /// <summary>
        /// Test the property 'OriginalInput'
        /// </summary>
        [Test]
        public void OriginalInputTest()
        {
            // TODO unit test for the property 'OriginalInput'
        }
        /// <summary>
        /// Test the property 'NormalizedResult'
        /// </summary>
        [Test]
        public void NormalizedResultTest()
        {
            // TODO unit test for the property 'NormalizedResult'
        }

    }

}
