/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing StringAutomaticThreatDetection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StringAutomaticThreatDetectionTests
    {
        // TODO uncomment below to declare an instance variable for StringAutomaticThreatDetection
        //private StringAutomaticThreatDetection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StringAutomaticThreatDetection
            //instance = new StringAutomaticThreatDetection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StringAutomaticThreatDetection
        /// </summary>
        [Test]
        public void StringAutomaticThreatDetectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StringAutomaticThreatDetection
            //Assert.IsInstanceOfType<StringAutomaticThreatDetection> (instance, "variable 'instance' is a StringAutomaticThreatDetection");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'ContainedJsonInsecureDeserializationAttack'
        /// </summary>
        [Test]
        public void ContainedJsonInsecureDeserializationAttackTest()
        {
            // TODO unit test for the property 'ContainedJsonInsecureDeserializationAttack'
        }
        /// <summary>
        /// Test the property 'ContainedXssThreat'
        /// </summary>
        [Test]
        public void ContainedXssThreatTest()
        {
            // TODO unit test for the property 'ContainedXssThreat'
        }
        /// <summary>
        /// Test the property 'ContainedXxeThreat'
        /// </summary>
        [Test]
        public void ContainedXxeThreatTest()
        {
            // TODO unit test for the property 'ContainedXxeThreat'
        }
        /// <summary>
        /// Test the property 'ContainedSqlInjectionThreat'
        /// </summary>
        [Test]
        public void ContainedSqlInjectionThreatTest()
        {
            // TODO unit test for the property 'ContainedSqlInjectionThreat'
        }
        /// <summary>
        /// Test the property 'ContainedSsrfThreat'
        /// </summary>
        [Test]
        public void ContainedSsrfThreatTest()
        {
            // TODO unit test for the property 'ContainedSsrfThreat'
        }
        /// <summary>
        /// Test the property 'IsXML'
        /// </summary>
        [Test]
        public void IsXMLTest()
        {
            // TODO unit test for the property 'IsXML'
        }
        /// <summary>
        /// Test the property 'IsJSON'
        /// </summary>
        [Test]
        public void IsJSONTest()
        {
            // TODO unit test for the property 'IsJSON'
        }
        /// <summary>
        /// Test the property 'IsURL'
        /// </summary>
        [Test]
        public void IsURLTest()
        {
            // TODO unit test for the property 'IsURL'
        }
        /// <summary>
        /// Test the property 'OriginalInput'
        /// </summary>
        [Test]
        public void OriginalInputTest()
        {
            // TODO unit test for the property 'OriginalInput'
        }

    }

}
