/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing ThreatDetectionBotCheckResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ThreatDetectionBotCheckResponseTests
    {
        // TODO uncomment below to declare an instance variable for ThreatDetectionBotCheckResponse
        //private ThreatDetectionBotCheckResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ThreatDetectionBotCheckResponse
            //instance = new ThreatDetectionBotCheckResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ThreatDetectionBotCheckResponse
        /// </summary>
        [Test]
        public void ThreatDetectionBotCheckResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ThreatDetectionBotCheckResponse
            //Assert.IsInstanceOfType<ThreatDetectionBotCheckResponse> (instance, "variable 'instance' is a ThreatDetectionBotCheckResponse");
        }


        /// <summary>
        /// Test the property 'IsBot'
        /// </summary>
        [Test]
        public void IsBotTest()
        {
            // TODO unit test for the property 'IsBot'
        }

    }

}
