/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing ThreatDetectionTorNodeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ThreatDetectionTorNodeResponseTests
    {
        // TODO uncomment below to declare an instance variable for ThreatDetectionTorNodeResponse
        //private ThreatDetectionTorNodeResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ThreatDetectionTorNodeResponse
            //instance = new ThreatDetectionTorNodeResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ThreatDetectionTorNodeResponse
        /// </summary>
        [Test]
        public void ThreatDetectionTorNodeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ThreatDetectionTorNodeResponse
            //Assert.IsInstanceOfType<ThreatDetectionTorNodeResponse> (instance, "variable 'instance' is a ThreatDetectionTorNodeResponse");
        }


        /// <summary>
        /// Test the property 'IsTorNode'
        /// </summary>
        [Test]
        public void IsTorNodeTest()
        {
            // TODO unit test for the property 'IsTorNode'
        }

    }

}
