/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing UrlSsrfThreatDetectionRequestFull
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UrlSsrfThreatDetectionRequestFullTests
    {
        // TODO uncomment below to declare an instance variable for UrlSsrfThreatDetectionRequestFull
        //private UrlSsrfThreatDetectionRequestFull instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UrlSsrfThreatDetectionRequestFull
            //instance = new UrlSsrfThreatDetectionRequestFull();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UrlSsrfThreatDetectionRequestFull
        /// </summary>
        [Test]
        public void UrlSsrfThreatDetectionRequestFullInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UrlSsrfThreatDetectionRequestFull
            //Assert.IsInstanceOfType<UrlSsrfThreatDetectionRequestFull> (instance, "variable 'instance' is a UrlSsrfThreatDetectionRequestFull");
        }


        /// <summary>
        /// Test the property 'URL'
        /// </summary>
        [Test]
        public void URLTest()
        {
            // TODO unit test for the property 'URL'
        }
        /// <summary>
        /// Test the property 'BlockedDomains'
        /// </summary>
        [Test]
        public void BlockedDomainsTest()
        {
            // TODO unit test for the property 'BlockedDomains'
        }

    }

}
