/* 
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Security.Api;
using Cloudmersive.APIClient.NET.Security.Model;
using Cloudmersive.APIClient.NET.Security.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Security.Test
{
    /// <summary>
    ///  Class for testing UrlSsrfThreatDetectionResponseFull
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UrlSsrfThreatDetectionResponseFullTests
    {
        // TODO uncomment below to declare an instance variable for UrlSsrfThreatDetectionResponseFull
        //private UrlSsrfThreatDetectionResponseFull instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UrlSsrfThreatDetectionResponseFull
            //instance = new UrlSsrfThreatDetectionResponseFull();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UrlSsrfThreatDetectionResponseFull
        /// </summary>
        [Test]
        public void UrlSsrfThreatDetectionResponseFullInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UrlSsrfThreatDetectionResponseFull
            //Assert.IsInstanceOfType<UrlSsrfThreatDetectionResponseFull> (instance, "variable 'instance' is a UrlSsrfThreatDetectionResponseFull");
        }


        /// <summary>
        /// Test the property 'CleanURL'
        /// </summary>
        [Test]
        public void CleanURLTest()
        {
            // TODO unit test for the property 'CleanURL'
        }
        /// <summary>
        /// Test the property 'ThreatLevel'
        /// </summary>
        [Test]
        public void ThreatLevelTest()
        {
            // TODO unit test for the property 'ThreatLevel'
        }

    }

}
